version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: ecom_pg
    environment:
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecompass
      POSTGRES_DB: ecom_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ecom_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata:
