name: dbt Compile

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dbt-compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ecom_dbt   # <— important: run inside your dbt project
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Show versions
        run: |
          dbt --version
          python -V

      - name: dbt deps
        run: dbt deps

      - name: dbt compile
        run: dbt compile
