name: dbt Compile

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dbt-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Useful when debugging paths
      - name: Show repo layout
        run: |
          pwd
          ls -la
          ls -la ecom_dbt || true

      - name: dbt --version
        run: dbt --version

      - name: dbt deps
        run: dbt deps --project-dir ecom_dbt

      - name: dbt compile
        run: dbt compile --project-dir ecom_dbt
